---
# docker-compose.yml
version: '3.9'
services:
  app:
    image: oven/bun
    container_name: linkshortener_vue_dev
    # override default entrypoint allows us to do `bun install` before serving
    entrypoint: []
    # execute bun install before we start the dev server in watch mode
    command: /bin/sh -c 'bun install && bun run dev --host'
    # expose the right ports
    ports: [5173:5173]
    # setup a host mounted volume to sync changes to the container
    volumes: [./:/home/bun/app]
